interglobalvision/pindropstudio-com

bower.json, css/grid.styl, css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, css/type.styl, footer.php, header.php, index.php, js/library.js, js/main.js, partials/pagination.php
- adds shuffle item style
- adds shuffle js
- adds style and markup for dotted dividers
- doesnt have drawer and overlay news functionality
=> Feature news style & scaffold

archive-luminaries.php, composer.json, composer.lock, css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, footer.php, js/main.js, lib/functions-filters.php, lib/meta-boxes.php, lib/post-types.php, partials/related-posts.php, single-luminaries.php
- adds post type
- scaffold index and single
- add base of related posts partial
- add sorting filters for archive
- needs full styling and image size handling (in future)
=> Feature scaffold luminaries

page.php
nothing actually uses this template but it seems a good basis for building out the rest of the custom pages
=> scaffold page

css/site.css, css/site.styl, js/main.js
=> Fix lint warnings

lib/meta-boxes.php, single-event.php
very basic framework. need answers from MA to do any details or AV functionality
=> Scaffold single event

archive-luminaries.php, lib/functions-custom.php, lib/functions-filters.php, lib/meta-boxes.php
- improves sorting with surname from metafield and better menu_order frontend
- adds menu_order column to admin
=> Details: luminaires archive

bower.json, css/library.styl, css/site.css, css/site.styl, functions.php, js/library.js, js/main.js, lib/custom-gallery.php, lib/functions-custom.php, lib/meta-boxes.php, single-event.php
- Adds media embed blocks from metaboxes
- Adds related luminaries
- Add gallery option to replace thumbnail
- Adds basic sitewide gallery support
- Adds swiper lib
=> Details: single Event

archive-luminaries.php, functions.php, lib/functions-custom.php, lib/functions-render.php, page-live.php, page-partners.php, page.php, partials/custom-pages/live/event-forthcoming.php, partials/pagination.php, partials/related-posts.php, single-event.php
The `grid-row` has been left out as that is often used for margin classes and sometimes might want an id etc. It could be included with more function vars to render classes and id if that is better?
=> Feature dividers

css/site.css, css/site.styl, js/main.js, lib/theme-options/home-options.php, lib/thumbnail-sizes.php, page-home.php, partials/custom-pages/home/carousel.php
This is missing the full content set in the slide as that isn’t yet clear. So this is just a styling and scaffolding and the content details are waiting question responses
=> Feature home carousel scaffold

css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, lib/theme-options/home-options.php, partials/custom-pages/home/carousel.php
- group field with override fields for title and image
- add conditional header
- style
=> Extend home carousel

css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, js/main.js, partials/custom-pages/home/carousel.php
=> Detail responsive carousel

css/site.css, css/type.styl, index.php, lib/functions-render.php, page-home.php
- center cards in rows on home
- assign italics and bold properly
- style read more
- style wide ad text
=> Details misc

lib/meta-boxes.php, page.php, partials/related-posts.php
Main purpose is to add related post support to pages (possibly for private pages)
- Adds related post support to pages
- Improves layout for more and less than 3 related posts
=> Detail related posts

functions.php
=> fix cmb2 wp update issue

page-home.php, page-live.php
- home s&v have media meta set
- forthcoming events sorted with soonest first
=> Fix queries

archive-event.php, functions.php, lib/functions-filters.php, lib/meta-boxes.php, page-live.php, page-sound-and-vision.php, partials/custom-pages/event-past.php
- Adds proper support for event archive and links too
- Adds override information for sound & vision sections of events
=> Feature event archive split

css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, footer.php, index.php, js/main.js
opens news thumbs into lightbox on click and hides on click
This seems really pointless so want to get feedback before continuing with this feature
=> Feature news lightbox scaffold

js/main.js
more or less just a change in the object name
=> rename news object to shuffle

css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, footer.php, js/main.js, partials/lightbox.php
- add close UI
- improve close click bind event
- restructure
=> Detail: Lightbox UI

page-sound-and-vision.php, partials/custom-pages/event-past.php
- dont show alt title on live page
- dont show location next to alt subtitle
=> Detail alt titles

css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css, css/type.styl, lib/meta-boxes.php, page-home.php, page-live.php, page-sound-and-vision.php, partials/custom-pages/event-forthcoming.php, partials/custom-pages/event-past.php, partials/custom-pages/home/tall-ads.php
- use conditional layout for Live page as well as Home
- add sold out support
- improve micro font style
=> Detail: Forthcoming events on Home and Live

css/responsive/mobile.styl, css/site.css, js/main.js, lib/functions-render.php, single-event.php
=> Feature: Share widget

partials/single-event/single-event-forthcoming.php, partials/single-event/single-event-more-forthcoming.php, partials/single-event/single-event-past.php, single-event.php
https://trello.com/c/Qslet74x/95-detail-single-event-forthcoming
=> Feature: forthcoming single event layout

css/responsive/desktop.styl, css/responsive/mobile.styl, css/responsive/tablet.styl, css/site.css
- stop logo overflow
- deal with multiline menus
- break line more sensibly for mid sizes
=> Responsive: Improve menu

js/main.js, lib/functions-render.php, partials/single-event/single-event-past.php
Soundcloud embeds now work with private tracks
=> Fix private soundcloud

archive-event.php, archive-people.php, css/grid.styl, css/site.css, css/site.styl, index.php, js/main.js, lib/functions-render.php, lib/meta-boxes.php, lib/post-types.php, lib/theme-options/about-options.php, page-about.php, page-partners.php, page-sound-and-vision.php, partials/people/person.php
- People Archive now displays 2 sections conditional on a checkbox being ticked or not
- Partners page now displays data from site options
- About now fills people and partners section with same layout and data from the archive and custom page
- Shuffle js needed to be restructure for new people layout
=> Restructure about, people and partners

partials/custom-pages/event-forthcoming.php, partials/custom-pages/event-past.php, partials/custom-pages/home/luminary-recent.php, single-event.php
mainly on homepage but also s&v, live and single event
=> Responsive: shift grid items to fit mobile

archive-luminaries.php, css/site.css, css/site.styl, js/main.js, page-sound-and-vision.php
uses text list in both instances
=> Details luminaries filters

css/responsive/desktop.styl, css/responsive/tablet.styl, css/site.css, css/site.styl, lib/functions-render.php, lib/theme-options/home-options.php, page-home.php, partials/custom-pages/event-forthcoming.php, partials/custom-pages/home/tall-ads.php
ref: https://trello.com/c/OPoRyb7T/117-homepage-edits link to html flat in there
=> Edits and details: home

page-home.php
limit final query and only get non override posts if needed
=> Fix: Home S&V overrides logic

css/responsive/mobile.styl, css/site.css
fixes the pixel jump for shareable and makes the border size work better
=> Detail: `.link-button` class

lib/functions-render.php
set correct links and link entire element
=> Fix: render_ad function

css/site.css, css/site.styl, lib/thumbnail-sizes.php
need to regenerate all images :/
=> Detail: match large grid size to mockup

page-live.php
- Use media shuffle section
- fix override query too
=> Detail: live past events

page-template-feature.php, partials/related-posts.php, partials/shuffle/shuffle-post.php
Now uses shuffle layout and matches to related post section on collection page template
=> Detail: Related posts

js/main.js, lib/functions-render.php, lib/thumbnail-sizes.php, partials/custom-pages/event-media.php, partials/custom-pages/home/carousel.php, partials/custom-pages/live/event-forthcoming.php
- Link areas
- Thumb size for S&V
- (also media playing changes)
=> Details: Homepage

css/site.css, css/site.styl, js/main.js, partials/custom-pages/event-media.php
- not Watch label only Play
- stop button for playing media
=> Detail: Media

archive-luminaries.php, lib/functions-filters.php
=> Detail: luminary index

css/site.css, css/site.styl, page-about.php, page-join.php, page-submit.php, page-template-feature.php, page.php
set max width of post copy to 620px and move containing divs so this can work
=> Detail: post copy width

css/site.css, css/site.styl, lib/functions-render.php, page-home.php, partials/custom-pages/event-forthcoming.php
- add missing margins
- improve wide ad for mobile
- scale tall ad images with ratio containing box
=> Details: Home

partials/custom-pages/event-media.php, partials/custom-pages/home/carousel.php
=> Fix: Time conditionals

404.php, archive-event.php, css/responsive/desktop.styl, css/responsive/tablet.styl, css/site.css, lib/functions-render.php, page-about.php, page-live.php, page-partners.php, page-sound-and-vision.php, page-template-feature.php, page.php, partials/custom-pages/event-forthcoming.php, partials/single-event/single-event-past.php
A range of minor edits or styling details. Commits explain purpose or intent
=> Details: Misc

css/responsive/tablet.styl, css/site.css, css/site.styl, lib/functions-render.php, partials/custom-pages/event-forthcoming.php
- fix image containing ratio box
- handle long titles differently
=> Detail: Tall ad

archive-event.php, page-live.php, partials/custom-pages/event-archive.php
- fix event archive button
- use event archive layout for live page past events
=> Details: Past events

css/site.css, css/site.styl
mobile/desktop binary doesnt align with the 3 stages of grid but this
was original intention
=> Fix: Desktop only utility

css/responsive/tablet.styl, css/site.css, css/site.styl, js/main.js, page-home.php, partials/custom-pages/event-forthcoming.php, partials/custom-pages/event-media.php, partials/custom-pages/home/tall-ads.php
only used on homepage (for now)
=> Feature: Layout height matching function

partials/custom-pages/event-archive.php, partials/shuffle/shuffle-post.php
- dont show date for luminaries or pages in grid layouts
- use metadata date for event archive
=> Detail: post dates

page-contact.php
=> Add: Contact page template

archive-luminaries.php, single-luminaries.php
have manually added this to server!!!
=> luminary index h3 to h4
